### ISSUE TITLE
PNGのヘッダからプロンプトを自動入力する機能

### ISSUE THREAD

**Issue by crstp** [riku1227/NovelAIManager#4]
NovelAIの画像を入れるだけでヘッダからプロンプトを自動入力できたら便利そうです
(ヘッダを見るだけのサイトはもうありますが、こういうビューアーで見れた方が便利なので)

**Comment by riku1227** [comment]
欲しい機能ですね
実装できるかやってみます～！

**Comment by riku1227** [comment]
とりあえずメタデータ読み込み機能追加しました！ cd4210f
次回更新から利用できるようになります！
  
![novel_ai_png_metadata_01](https://user-images.githubusercontent.com/17927874/200005226-aa1d41d4-c651-43ec-a5f9-ada839b35198.png)
![novel_ai_png_metadata_02](https://user-images.githubusercontent.com/17927874/200005235-8f5badf2-2bca-434b-badb-ec5451fcedb6.png)

**Comment by crstp** [comment]
早速ありがとうございます！楽しみです
